site_name: The Tome Of All Tomes
site_url: https://the-incipisphere.github.io/The-Tome-Of-All-Tomes/

repo_name: The Tome Of All Tomes
repo_url: https://github.com/The-Incipisphere/The-Tome-Of-All-Tomes

theme:
  name: material
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
