site_name: The Tome Of All Tomes
site_url: https://the-incipisphere.github.io/The-Tome-Of-All-Tomes/

repo_name: The Tome Of All Tomes
repo_url: https://github.com/The-Incipisphere/The-Tome-Of-All-Tomes

theme:
  name: material
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - content.code.annotate
    - content.action.view

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret:
      insert: false
  - pymdownx.tilde:
      delete: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
